name: youtube-view-fetch

on:
  schedule:
    - cron: "51 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install google-api-python-client
          pip install pandas

      - name: Run fetch
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4   # ← 修正ポイント
        with:
          name: csv
          path: view_history_hourly.csv

  commit:
    needs: fetch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
          clean: false

      - name: Download CSV
        uses: actions/download-artifact@v4   # ← 修正ポイント
        with:
          name: csv

      - name: Commit CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add view_history_hourly.csv
          git commit -m "Update CSV" || echo "No changes"
          git push

  analysis:
    needs: commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: false

      - name: Download CSV
        uses: actions/download-artifact@v4
        with:
          name: csv

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install pandas matplotlib tabulate
          sudo apt-get update
          sudo apt-get install -y fonts-ipafont

      - name: Run analysis
        run: python analysis.py

      - name: Upload analysis report
        uses: actions/upload-artifact@v4
        with:
          name: analysis
          path: |
            analysis_report.md
            graph_*.png

