name: youtube-view-fetch

on:
  schedule:
    - cron: "2 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true
          path: .

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install google-api-python-client
          pip install pandas

      - name: Run script
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch.py

      - name: Commit CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add view_history_hourly.csv
          git commit -m "Update CSV" || echo "No changes to commit"
          git push
